import mongoose from "mongoose";

const taskSchema = new mongoose.Schema(
    {
        userId: {
            type: String,
            required: true,
            index: true,
            description: "User ID"
        },
        subjectId: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "Subject",
            required: true,
            index: true,
            description: "Subject ID"
        },

        title: {
            type: String,
            required: true,
            default: "Calculus Practice",
            description: "Task title"
        },
        description: {
            type: String,
            default: "",
            description: "Task description"
        },

        estimatedMinutes: {
            type: Number,
            required: true,
            description: "Estimated minutes for the task"
        },
        scheduledDate: {
            type: Date,
            required: true,
            default: Date.now,
            description: "Scheduled date for the task"
        },

        priority: {
            type: String,
            enum: ['critical', 'high', 'medium', 'low'],
            description: "Priority of the task"
        },

        urgencyScore: {
            type: Number,
            default: 0,
            min: 0,
            max: 100,
            description: "Urgency score of the task"
        },

        status: {
            type: String,
            enum: ['pending', 'in_progress', 'completed', 'skipped'],
            default: 'pending',
            description: "Status of the task"
        },

        completionPercentage: {
            type: Number,
            default: 0,
            min: 0,
            max: 100,
            description: "Completion percentage of the task"
        },
        actualMinutesSpent: {
            type: Number,
            default: 0,
            min: 0,
            description: "Actual minutes spent on the task"
        },

        linkedSessionId: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "StudySession",
            description: "Linked study session ID"
        },

        generatedBy: {
            type: String,
            enum: ['system', 'user'],
            description: "Generated by system or user"
        },
        isRecurring: {
            type: Boolean,
            default: false,
            description: "Is the task recurring"
        },
    },
    {
        timestamps: true
    }
);

export const Task = mongoose.model("Task", taskSchema);

